_BASE_: "/home/rileymcnamara09/Australian-Medical-Form-Scanner/.venv/lib/python3.8/site-packages/detectron2/model_zoo/configs/COCO-Detection/fast_rcnn_R_50_FPN_1x.yaml"

MODEL:
  PROPOSAL_GENERATOR:
    NAME: "RPN"
  LOAD_PROPOSALS: False
  WEIGHTS: "/home/rileymcnamara09/Australian-Medical-Form-Scanner/models/pretrained/pretrained1.pkl"
  ROI_HEADS:
    NUM_CLASSES: 9

DATASETS:
  TRAIN: ("my_train_dataset",)
  TEST: ("my_val_dataset",)

SOLVER:
  IMS_PER_BATCH: 4
  MAX_ITER: 2000
  BASE_LR: 0.001

INPUT:
  MIN_SIZE_TRAIN: (600,)
  MAX_SIZE_TRAIN: 1000

DATALOADER:
  NUM_WORKERS: 4


OUTPUT_DIR: "/home/rileymcnamara09/Australian-Medical-Form-Scanner/models/trained"
